name: Python Run

on:
  push:
    branches: ["main"]
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      -uses: action/checkout@v3
      -uses: action/setup-python@v4
      with:
        python-version: '3.10'
      -run: python hello.py

     
      
